name: deep_research
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
      - torch==2.9.0
      - transformers==4.57.1
      - ddgs==9.4.0
      - langchain==1.0.0
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==1.0.0
      - langchain-ollama==1.0.0
      - langchain-openai==1.0.0
      - openai==2.5.0
      - jupyter==1.1.1
      - ipykernel==6.29.5
