name: rag-chatbot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain==1.0.0
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==1.0.0
      - langchain-huggingface==1.0.0
      - langchain-ollama==1.0.0
      - langchain-openai==1.0.0
      - langchain-text-splitters==1.0.0
      - sentence-transformers==5.1.1
      - streamlit==1.50.0
      - openai==2.5.0
      - faiss-cpu==1.12.0
      - unstructured==0.18.5
